### ISSUE TITLE
Move to jslicense

### ISSUE THREAD

**Issue by kemitchell** [jslicense/spdx-correct.js#15]
@zommerfelds especially, any objection to moving this repo into https://github.com/jslicense?  I'd add you as collaborator there, too.

I might move my other spdx- packages there, as well.  I've done a lot of work on these packages, but even where I wrote all the code so far, they've always benefited from lots of input from lots of folks.  I don't want to overshadow that by having my handle in the location bar all the time.

**Comment by zommerfelds** [comment]
Sure, no objections. Is that your project/org?

**Comment by zommerfelds** [comment]
Accepted your invite.
