### ISSUE TITLE
lower-case `or` in spdx expression fails

### ISSUE THREAD

**Issue by drewfish** [jslicense/spdx-correct.js#16]
Version `2.5.0` of `jszip` package has a license field of `MIT or GPLv3` which gets intepreted as `GPL-3.0`. When I upper-case the `or` to `OR` I get the correct value of `MIT OR GPL-3.0`.

This is probably pretty low priority since jszip@3.1.3 (dist-tag `latest` as of this writing) has a license field which works well.

**Comment by drewfish** [comment]
Oh hmm... should this issue be filed on the spdx-expression-parse package instead?

**Comment by drewfish** [comment]
Double-hmm... the SPDX-2.1 spec makes reference to `"OR"`. Without explicitly discussing which upper-/lower-case (or mixed) is allowed I guess that means it needs to be upper-case.

**Comment by kemitchell** [comment]
@drewfish, `MIT or GPLv3` isn't a valid SPDX expression.  Current 3.1.3 has it right.
