### ISSUE TITLE
TARBALL_INTEGRITY failing when installing with PNPM

### ISSUE THREAD

**Issue by sriharshachilakapati** [jslicense/spdx-correct.js#35]
I'm getting this message when trying to install with PNPM. 

> WARN  GET https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.1.1.tgz error (ERR_PNPM_TARBALL_INTEGRITY). Will retry in 10 seconds. 2 retries left.
 ERROR  Got unexpected checksum for "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.1.1.tgz". Wanted "sha512-lr2EZCctC2BNR7j7WzJ2FpDznxky1sjfxvvYEyzxNyb6lZXHODmEoJeFu4JupYlkfha1KZpJyoqiJ7pgA1qq8Q==". Got "sha512-cOYcUWwhCuHCXi49RhFRCyJEK3iPj1Ziz9DpViV3tbZOwXD49QzIN3MpOLJNxh2qwq2lJJZaKMVw9qNi4jTC0w==".

How to resolve this? Can you check?

**Comment by sriharshachilakapati** [comment]
Please do state the reason for closing the issue. I'm confused, isn't it a security issue from the NPM registry?

**Comment by kemitchell** [comment]
I'm sure you have an issue, but I don't think it's my issue. This package is not the place for pnpm or npm support.

**Comment by sriharshachilakapati** [comment]
I thought something could've been happened when you are pushing artifacts to the registry as this is happening with only your package. I'll also raise this with the PNPM team to be sure.
