### ISSUE TITLE
`spdx-correct` throws "Most NODE_OPTIONs are not supported..." error.

### ISSUE THREAD

**Issue by Rogue3799** [jslicense/spdx-correct.js#42]
I'm not exactly sure what this package does. I'm not using it directly, but Storybook.js seems to call this to startup an application. I'm getting the following error message when it tries to start:

```sh
[26464:1206/164139.619:ERROR:node_bindings.cc(303)] 
Most NODE_OPTIONs are not supported in packaged apps.
```

The script which calls `spdx-correct/index.js` is this:
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

exec "$basedir/../spdx-correct/index.js" "$@"
```

Any ideas on how to fix this?

**Comment by kemitchell** [comment]
That Bourne script appears to be calling code in this package, but that script is not our code. You will need to take your code up with whoever's responsible for it.
