### ISSUE TITLE
GPL-2.0-only is returned for EPL-1.0_OR_LGPL-2.1

### ISSUE THREAD

**Issue by dac2k21** [jslicense/spdx-correct.js#45]
Sending in `(EPL-1.0 OR LGPL-2.1)`, returns `'EPL-1.0 OR LGPL-2.1',` but if I add underscore `EPL-1.0_OR_LGPL-2.1 `I will get `GPL-2.0-only` as the response. Not sure if fixable but would be nice with either the same response or undefined for `EPL-1.0_OR_LGPL-2.1`.

**Comment by kemitchell** [comment]
Underscores aren't close to valid SPDX syntax. I doubt this package will ever support suggestion of compound expression with `OR` or `AND`.
